### ISSUE TITLE
Make Navbar More Interactive

### ISSUE THREAD

**Issue by geeks5551** [geeks5551/iCoderBootStrap#1]
Make the Navbar More Interactive Using Advanced CSS Effects Like Animation And Transition Effects etc

**Comment by oshyam** [comment]
Hi, I would like to contribute.

**Comment by geeks5551** [comment]
sure @oshyam , Go ahead!!

**Comment by kittu2karthik** [comment]
hey @geeks5551 . i am searching for projects and issue for my very first hacktoberfest contributions and this looks very perfect for me .. can you please assign it to me 
thanks in advance

**Comment by geeks5551** [comment]
ya sure @kitttu2karthik go ahead!!

**Comment by geeks5551** [comment]
@oshyam Any Updates??

**Comment by iamrishavraj1** [comment]
Hello, Can You Please Assign me This Issue

**Comment by kumarmanish03** [comment]
@oshyam @iamrishavraj1 @kittu2karthik Hey, you may contribute to this repo as well.
https://github.com/CoffeeWithDevs/CodeWithUs
 Do have a look

**Comment by iamrishavraj1** [comment]
> @oshyam @iamrishavraj1 @kittu2karthik Hey, you may contribute to this repo as well.
> https://github.com/CoffeeWithDevs/CodeWithUs
> Do have a look

Why Not..! Let Me Check The Issue..!
