### ISSUE TITLE
Design Contact Us Page

### ISSUE THREAD

**Issue by geeks5551** [geeks5551/iCoderBootStrap#10]
presently There is No Contact Us Page To the Main Website, design and link a relatable Contact Us Page With the Home Page
Also Provide with the screenshots/Live Link for better reviewing the pr

**Comment by namrata18s** [comment]
Hi Can you assign it to me!

**Comment by geeks5551** [comment]
Ya Sure @namrata18s Go Ahead!!

**Comment by namrata18s** [comment]
actually I could see already a contact page. should I create a seperate contact us page or enhance previously created one?

**Comment by namrata18s** [comment]
created the pull request #15 .Please review PR.

![image](https://user-images.githubusercontent.com/19836546/97091717-8ab6c180-165b-11eb-8cd6-eca54f021f65.png)

**Comment by iamrishavraj1** [comment]
Hey, Can You Please Assign me This Issue..

**Comment by geeks5551** [comment]
close #10 by #15
