### ISSUE TITLE
Add A Suitable Icon to the Navbar

### ISSUE THREAD

**Issue by geeks5551** [geeks5551/iCoderBootStrap#11]
presently There is No Icon to the Navbar , Design And Add A Relatable Icon to the Navbar(which should clearly relate  to the main website)
Also Provide with the screenshots/Live Link for better reviewing the pr

**Comment by kittu2karthik** [comment]
hey @geeks5551 
 i am searching for projects and issue for my very first hacktoberfest contributions and this looks very perfect for me .. can you please assign it to me 
thanks in advance

**Comment by geeks5551** [comment]
@kitttu2karthik go ahead!!

**Comment by iamrishavraj1** [comment]
Hey,Can You Assign me for this issue..

**Comment by kittu2karthik** [comment]
I have added icons to the navbar..... when I push the code ... I am getting an error.... can you help to resolve this
![Screenshot (14)](https://user-images.githubusercontent.com/71444538/97095468-610e9200-167d-11eb-9d9a-efbe504c1d47.png)

**Comment by iamrishavraj1** [comment]
> I have added icons to the navbar..... when I push the code ... I am getting an error.... can you help to resolve this
> ![Screenshot (14)](https://user-images.githubusercontent.com/71444538/97095468-610e9200-167d-11eb-9d9a-efbe504c1d47.png)
@kitttu2karthik 
Hey, You wrote Command. Please Command This *git push -u origin* or *git push -u <branchName>* .

**Comment by juyoungk23** [comment]
Hey @geeks5551 , I'd like to contribute to this! Could you assign this to me? Thanks
