### ISSUE TITLE
Add A favicon To the Title of the Main Website In the Browser

### ISSUE THREAD

**Issue by geeks5551** [geeks5551/iCoderBootStrap#12]
presently There is No Favicon to the Title  , Design And Add A Relatable Favicon to the Title(which should clearly relate  to the main website)
Also Provide with the screenshots/Live Link for better reviewing the pr

**Comment by kittu2karthik** [comment]
hey @geeks5551 
this looks very perfect for me .. 
can you please assign it to me...

**Comment by geeks5551** [comment]
@kitttu2karthik great to see your active participation, you have already two issues assigned first complete those, let other's also have a chance
