### ISSUE TITLE
Add Scroll To Top Button 

### ISSUE THREAD

**Issue by geeks5551** [geeks5551/iCoderBootStrap#2]
Add The Scroll To Top Button At The Bottom Right Corner Of Page Which should Be Seen Only On Scrolling Down And Not Originally. Also, Make Sure On clicking on it we should move gradually Upwards And Not Suddenly. Add A proper Icon To This Button

**Comment by snehaa1989** [comment]
assign to me

**Comment by geeks5551** [comment]
@snehaa1989 go ahead!!

**Comment by snehaa1989** [comment]
@geeks5551 i have made a PR, check it out

**Comment by omarobaji** [comment]
I would like to do this aswell if possible, Just for participating in hacktoberfest

**Comment by geeks5551** [comment]
> @geeks5551 i have made a PR, check it out
  Hey can you send/provide   a live link or screen shot of the changes you have made .

**Comment by geeks5551** [comment]
> I would like to do this as well if possible, Just for participating in hacktoberfest

thanks for showing your interest in the repo, but the issue is already assigned to somebody else , so I can't assign it to you untill I have to unassign the first one , it is strictly on the basis of first come first serve, however you can keep on visiting this repo as more issues are going to open

**Comment by kumarmanish03** [comment]
@omarobaji Hey you contribute to the given repo https://github.com/CoffeeWithDevs/CodeWithUs

**Comment by kumarmanish03** [comment]
Hey, @snehaa1989 @georgioupanayiotis @omarobaji 
You may also check out this repo https://github.com/CoffeeWithDevs/CodeWithUs
