### ISSUE TITLE
Design Contact Us Page

### ISSUE THREAD

**Issue by geeks5551** [geeks5551/iCoderBootStrap#21]
Design A contact us page and attach it with home page, leave a live link/screenshot for better reviewing

**Comment by slytherin20** [comment]
Hi @geeks5551,
Can I work on this?

**Comment by geeks5551** [comment]
@slytherin20 go ahead!!

**Comment by slytherin20** [comment]
@geeks5551 I noticed there is already a contact us page attached to the homepage. Do you need the restyling of this page?

**Comment by iamrishavraj1** [comment]
hey Can You Please Assign me for this Issue?

**Comment by geeks5551** [comment]
> @geeks5551 I noticed there is already a contact us page attached to the homepage. Do you need the restyling of this page?

ya you can edit that page

**Comment by geeks5551** [comment]
hey @slytherin20 any updates??

**Comment by slytherin20** [comment]
@geeks5551 Will be sending the PR by tomorrow with the live link attached.
