### ISSUE TITLE
Design About Us Page

### ISSUE THREAD

**Issue by geeks5551** [geeks5551/iCoderBootStrap#23]
Design About Us page  and connect it with home page, Leave a live link/screenshot for better reviewing

**Comment by ghost** [comment]
Hey, @geeks5551 ...I am searching for project & for my very first hacktoberfest 2020 this look very prefect for me.Can you assign it to me???😊😊 thanks in advance.

**Comment by geeks5551** [comment]
@paromitadas2903 Go Ahead!!

**Comment by ghost** [comment]
@geeks5551 thank you so much 😊😊😊

**Comment by geeks5551** [comment]
hey @paromitadas2903 any updates??

**Comment by ghost** [comment]
@geeks5551 sorry to inform you😣 that ..my laptop got some issues😔...so i am unable to work on..it!!!soon I will give you updates.

**Comment by geeks5551** [comment]
hey @paromitadas2903 you can work on this issue till any other person is not claiming it

**Comment by ghost** [comment]
@geeks5551 okkk!!!

**Comment by geeks5551** [comment]
@paromitadas2903 Any updates??

**Comment by cunning-weasel** [comment]
@geeks5551 can I take a look at this? Perhaps too late for the fest but I don't mind 😄

**Comment by geeks5551** [comment]
okk @cunning-weasel go ahead!!
