### ISSUE TITLE
Duplicate Nav-Items in Navbar

### ISSUE THREAD

**Issue by iamrishavraj1** [geeks5551/iCoderBootStrap#24]
![screencapture-file-C-Users-iamri-OneDrive-Desktop-iCoderBootStrap-index-html-2020-10-30-19_07_24](https://user-images.githubusercontent.com/62508858/97711714-72272b00-1ae3-11eb-8095-7cac26fa4491.png)
 Hey, I think There is Some Duplicate Nav Items in Navbar.. May I remove This Issue or Leave as it? @geeks5551

**Comment by geeks5551** [comment]
ya maybe someone has done navbar customization wrongly, you can go ahead with this issue, but leave a screenshot/live link for better reviewing, also beautify the navbar without affecting the main theme

**Comment by geeks5551** [comment]
hey @iamrishavraj1 any updates??

**Comment by iamrishavraj1** [comment]
![Uploading screencapture-file-C-Users-iamri-OneDrive-Desktop-iCoderBootStrap-index-html-2020-10-31-00_10_03.png…]()
Hey @geeks5551 I already solve this issue Yesterday.

**Comment by iamrishavraj1** [comment]
![Uploading screencapture-file-C-Users-iamri-OneDrive-Desktop-iCoderBootStrap-index-html-2020-10-31-00_10_03.png…]()

**Comment by iamrishavraj1** [comment]
![Uploading screencapture-file-C-Users-iamri-OneDrive-Desktop-iCoderBootStrap-index-html-2020-10-31-00_00_30.png…]()

**Comment by iamrishavraj1** [comment]
hey @geeks5551 I already Solve this Issue Yesterday

**Comment by geeks5551** [comment]
ohh i see you have solved that  issue with navbar designing , okk fine @iamrishavraj1 i am closing this issue then
