### ISSUE TITLE
Update Readme.md File 

### ISSUE THREAD

**Issue by geeks5551** [geeks5551/iCoderBootStrap#4]
Make the file more informative and designed which should be based fully on the idea of the project which you can decipher after going through the codes/files

**Comment by georgioupanayiotis** [comment]
@geeks5551 can you assign me this ?

**Comment by geeks5551** [comment]
@georgioupanayiotis go ahead!!

**Comment by georgioupanayiotis** [comment]
@geeks5551 I have created the PR https://github.com/geeks5551/iCoderBootStrap/pull/5

**Comment by kittu2karthik** [comment]
hey @geeks5551 can assign me this issue
