### ISSUE TITLE
Add Responsive Footer in the Home Page

### ISSUE THREAD

**Issue by geeks5551** [geeks5551/iCoderBootStrap#7]
Add A Responsive Footer To The Home Page using Advanced CSS effects like Animations and Transitions,  
Also, provide live link/ Screenshots for better reviewing the pr

**Comment by kittu2karthik** [comment]
hey @geeks5551 
can u please assign  me 
I can add a responsive footer

**Comment by iamrishavraj1** [comment]
Hey,Can You Please Assign me This Issue..

**Comment by geeks5551** [comment]
@iamrishavraj1 go ahead!!

**Comment by geeks5551** [comment]
@kitttu2karthik great to see  your active participation,  you have already two issues assigned first complete those , let other's also have a chance

**Comment by iamrishavraj1** [comment]
Thanks For Assign me.. I Sent You PR please Review My PR

**Comment by geeks5551** [comment]
hey @iamrishavraj1 can you send live link/screenshots also for better reviewing

**Comment by iamrishavraj1** [comment]
> hey @iamrishavraj1 can you send live link/screenshots also for better reviewing

![screencapture-file-C-Users-iamri-OneDrive-Desktop-iCoderBootStrap-index-html-2020-10-25-01_50_41](https://user-images.githubusercontent.com/62508858/97092836-d457da00-1664-11eb-90cf-38419f0cc4b8.png)
![screencapture-file-C-Users-iamri-OneDrive-Desktop-iCoderBootStrap-index-html-2020-10-25-01_50_18](https://user-images.githubusercontent.com/62508858/97092838-d6ba3400-1664-11eb-925c-67323c06213c.png)

**Comment by iamrishavraj1** [comment]
Done Sir.

**Comment by geeks5551** [comment]
hey @iamrishavraj1 content of footer is fine but you can add more styling to it as well as make separate buttons for google , FB etc,
also you can ommit that copyright portion, rest is good

**Comment by iamrishavraj1** [comment]
> hey @iamrishavraj1 content of footer is fine but you can add more styling to it as well as make separate buttons for google , FB etc,
> also you can ommit that copyright portion, rest is good

Yaa I will..Actually The Issue Heading is Responsive That why I dont design to much..! Sorry for that..
I will change it And Make More Stylish..!

**Comment by iamrishavraj1** [comment]
![screencapture-file-C-Users-iamri-OneDrive-Desktop-iCoderBootStrap-index-html-2020-10-25-08_56_27](https://user-images.githubusercontent.com/62508858/97098185-1baf8c00-16a0-11eb-850f-b4573326558b.png)
![screencapture-file-C-Users-iamri-OneDrive-Desktop-iCoderBootStrap-index-html-2020-10-25-08_56_03](https://user-images.githubusercontent.com/62508858/97098188-20744000-16a0-11eb-9a74-3631abd20132.png)

**Comment by iamrishavraj1** [comment]
Done Can You Please Review My PR

**Comment by iamrishavraj1** [comment]
![screencapture-file-C-Users-iamri-OneDrive-Desktop-iCoderBootStrap-index-html-2020-10-25-10_13_34](https://user-images.githubusercontent.com/62508858/97099093-d47ac880-16aa-11eb-9436-d363d782f32f.png)
![Uploading screencapture-file-C-Users-iamri-OneDrive-Desktop-iCoderBootStrap-index-html-2020-10-25-10_13_22.png…]()

**Comment by iamrishavraj1** [comment]
![Uploading screencapture-file-C-Users-iamri-OneDrive-Desktop-iCoderBootStrap-index-html-2020-10-25-10_13_34.png…]()

**Comment by iamrishavraj1** [comment]
![screencapture-file-C-Users-iamri-OneDrive-Desktop-iCoderBootStrap-index-html-2020-10-25-10_13_34](https://user-images.githubusercontent.com/62508858/97099149-90d48e80-16ab-11eb-847a-9a08e900152c.png)
![screencapture-file-C-Users-iamri-OneDrive-Desktop-iCoderBootStrap-index-html-2020-10-25-10_13_22](https://user-images.githubusercontent.com/62508858/97099150-929e5200-16ab-11eb-8288-164a3c886209.png)

**Comment by geeks5551** [comment]
closed #7 by #16
