### ISSUE TITLE
Change The Background Of the Home Page

### ISSUE THREAD

**Issue by geeks5551** [geeks5551/iCoderBootStrap#8]
presently The Basic Background of the home page is whittish, Add Some relatable background images to it.
Also provide with the screenshots/live link for better reviewing purposes

**Comment by namrata18s** [comment]
Please assign it to me.
Thanks!!

**Comment by geeks5551** [comment]
ya sure @namrata18s go ahead!!

**Comment by geeks5551** [comment]
@namrata18s any updates??are you working on this issue

**Comment by namrata18s** [comment]
yes I am working on it & will update soon

**Comment by rachitmanas** [comment]
Can I also work on it?

**Comment by kumarmanish03** [comment]
@rachitmanas @namrata18s You may also check out this repo https://github.com/CoffeeWithDevs/CodeWithUs

**Comment by namrata18s** [comment]
Please review my PR #20
