### ISSUE TITLE
Design About Page 

### ISSUE THREAD

**Issue by geeks5551** [geeks5551/iCoderBootStrap#9]
presently There is No About Us Page To the Main Website, design and link a relatable About Us Page With the Home Page
Also Provide with the screenshots/Live Link for better reviewing the pr

**Comment by kittu2karthik** [comment]
hey @geeks5551 
I can design an About page....  with responsiveness

**Comment by geeks5551** [comment]
@kitttu2karthik  great to see your active participation, you have already two issues assigned first complete those , let other's also have a chance

**Comment by geeks5551** [comment]
go ahead @kittu2karthik

**Comment by geeks5551** [comment]
@kittu2karthik any updates??
